name: vCenter – List all VMs

on:
  workflow_dispatch:          # manual trigger
  #schedule:
   # - cron: '0 2 * * *'       # daily at 02:00 UTC (remove if not needed)

jobs:
  list-vms:
    runs-on: windows-latest

    env:
      VCENTER_SERVER: ${{ secrets.VCENTER_SERVER }}
      VCENTER_USER:   ${{ secrets.VCENTER_USER }}
      VCENTER_PASS:   ${{ secrets.VCENTER_PASS }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Install VMware PowerCLI (allow overwrite of existing cmdlets)
      - name: Install VMware PowerCLI
        shell: pwsh
        run: |
          if (-not (Get-Module -ListAvailable -Name VMware.PowerCLI)) {
            Install-Module -Name VMware.PowerCLI -Scope CurrentUser -Force -AllowClobber
          }
          # Suppress cert warnings
          Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false

      # Connect to vCenter and export VM list
      - name: Generate VM inventory CSV
        shell: pwsh
        run: |
          $securePwd = ConvertTo-SecureString $env:VCENTER_PASS -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ($env:VCENTER_USER, $securePwd)

          Connect-VIServer -Server $env:VCENTER_SERVER -Credential $cred | Out-Null

          Get-VM | Select Name, PowerState, @{N='Cluster';E={$_.VMHost.Parent.Name}} |
            Sort Name |
            Export-Csv -NoTypeInformation -Path vms.csv

          Disconnect-VIServer * -Confirm:$false

      # Upload CSV as artifact
      - name: Upload VM list artifact
        uses: actions/upload-artifact@v4
        with:
          name: vcenter-vm-list
          path: vms.csv
