name: vCenter VM Report

on:
  workflow_dispatch:        # manual trigger

jobs:
  fetch-vms:
    name: Generate VM List from vCenter
    runs-on: windows-latest

    env:
      VCENTER_SERVER: ${{ secrets.VCENTER_SERVER }}
      VCENTER_USER:   ${{ secrets.VCENTER_USER }}
      VCENTER_PASS:   ${{ secrets.VCENTER_PASS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run VM list script
        shell: pwsh
        run: |
          # Invoke your existing script
          .\Thames\vm_list.ps1 `
            -Server   $env:VCENTER_SERVER `
            -User     $env:VCENTER_USER `
            -Password $env:VCENTER_PASS `
            -OutFile  vms.csv

      - name: Upload VM list artifact
        uses: actions/upload-artifact@v4
        with:
          name: vcenter-vm-list
          path: vms.csv
